### PR TITLE
Feature: add line selection option

### PR DESCRIPTION
**Pull request by rgerstenberger**
This adds the ability to pass in a `selection` to be highlighted. `selection={{startLine: 2, endLine: 4}}` both `endLine` and `startLine` are inclusive. To highlight a single line pass in the same line number for both start and end. Uses `CodeMirror-activeline-background` class under the hood to allow for theming.

screen shot 2016-04-06 at 12 06 16 pm

### CODE REVIEW

**Comment by alexlande** [comment]
LGTM

I could see a use case for an array of selections in the future, potentially.

**Comment by rgerstenberger** [comment]
@alexlande I wasn't sure about the API, I considered an array of lines. Maybe that's simpler and more flexible overall?

e.g. `selectedLines={[1, 2, 6, 7, 8]}` or `selectedLines={[3]}`

**Comment by alexlande** [comment]
Oh yeah, that would be a lot more flexible, I think. (And would make way more sense than an array of selection objects, haha)

**Comment by rgerstenberger** [comment]
@alexlande switched to `selectedLines: array` API. Please re-review, thanks!

**Comment by alexlande** [comment]
Ship it!

**Pull request merged**
