### PR TITLE
Include CodeMirror in Component-Playground

### LINKED ISSUE #34: build codemirror in
I'm curious why code mirror needs to be included on the page vs. being a node module of this project.

### PR DESCRIPTION
**Pull request by NogsMPLS**
PR should fix #34 

Also note, while this removes the need to include codemirror javascript scripts in html for projects, the codemirror css will still be required.

### CODE REVIEW

**Comment by NogsMPLS** [comment]
ah crap, failed test. I'll check.

**Comment by NogsMPLS** [comment]
looks like a lint definition was updated recently? Also unsure how this is happening as `preview.jsx` is untouched:

```
ERROR in ./src/components/preview.jsx
Module not found: Error: Cannot resolve module 'react-dom/server' in /home/travis/build/FormidableLabs/component-playground/src/components
 @ ./src/components/preview.jsx 15:14-41
```

**Comment by NogsMPLS** [comment]
can't run lint on Windows looks like, so I'll have to use the CI here to check it with a few commits.

**Comment by NogsMPLS** [comment]
Ah, updated the repo's eslint from 0.24.1 -> 9.0.0 fixes that. I'll hopefully have a working PR sometime tomorrow

**Comment by NogsMPLS** [comment]
expect this latest commit to fail, testing new eslint package bump on ci.

**Comment by NogsMPLS** [comment]
Apologies for the massive commit count, I'm running on a windows machine and there seem to be some things only the CI catches.

**Comment by NogsMPLS** [comment]
Okay, so, this is now passing on Node 0.12.x, but failing on node 0.10.x.

Does component-playground officially support node 0.10.x?

**Comment by ryan-roemer** [comment]
The build failure looks spurious (?) 

```
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  Error: Cannot find module "react-dom"
  at /home/travis/build/FormidableLabs/component-playground/test/client/main.js:37663
INFO [Firefox 31.0.0 (Linux 0.0.0)]: Connected on socket WR1hrTLYMIgl9IgeyTom with id 74267187
Firefox 31.0.0 (Linux 0.0.0) ERROR
  Error: Cannot find module "react-dom"
  at /home/travis/build/FormidableLabs/component-playground/test/client/main.js:37663
PhantomJS 1.9.8 (Linux 0.0.0): Executed 0 of 0 ERROR (0.625 secs / 0 secs)
Firefox 31.0.0 (Linux 0.0.0): Executed 0 of 0 ERROR (0.34 secs / 0 secs)
```

I've restarted the build.

**Comment by ryan-roemer** [comment]
Side note `0.10` has npm v `1.4.29` by default. May be worth adding something like:

```yaml
before_install:
  - npm install -g npm@3
```

to `.travis.yml`

**Comment by NogsMPLS** [comment]
yeah, i was thinking similar, but wasn't sure if I should commit something that affects the CI build process without Formidable buy-in.

**Comment by ryan-roemer** [comment]
@NogsMPLS -- We failed on the same `react-dom` thing here too. Go ahead and add 

```
before_install:
  - npm install -g npm@3
```

to the `.travis.yml`

**Comment by NogsMPLS** [comment]
haha...hmmm maybe npm @2? lol

**Comment by NogsMPLS** [comment]
actually, i bet it's the whole 'peerDependency' thing. Was valid in npm2, not in 3. Let me move those to just straight dependencies, i think that'll fix it.

**Comment by NogsMPLS** [comment]
:tada: :notes: :trumpet: :notes: :tada:

**Comment by NogsMPLS** [comment]
so in addition to fixing #34 this PR also fixes #52 

And the latest commit should fix #56 as well.

**Comment by NogsMPLS** [comment]
pretty sure this should be good for merge and *hopefully* a new tagged release.

Let me know if there is anything not addressed in here and I'll see to it.

**Comment by kenwheeler** [comment]
I'll get this reviewed in the next day or so, with a release cut shortly thereafter. Thanks!

**Comment by NogsMPLS** [comment]
:+1:

**Pull request merged**
